### PR TITLE
Jaws revert temp fixes

### LINKED ISSUE #90: Remove JAWS double-escape workaround
We need to revert PR #89 after JAWS internally fixes the double escaping issue: 
https://github.com/w3c/aria-at-automation-harness/pull/89/files#diff-cdd0c3c00e18ab3f2da1b2c69511aee05eaa623a46db542a99c0b14ab1084f4dR355

### LINKED ISSUE #91: Simplify mode switch logic for JAWS
[We have implemented a somewhat surprising algorithm for changing the mode in JAWS](https://github.com/w3c/aria-at-automation-harness/pull/88) due to particulars around how that AT vocalizes mode changes. The algorithm could be made much more legible with the use of the "getSettings" command. Unfortunately, JAWS does not currently implement "getSettings".

Simplify the underlying logic once JAWS supports "getSettings".

### PR DESCRIPTION
**Pull request by gnarf**
Fixes for the temporary changes now that the new version of JAWS properly encodes and has getSettings

Closes #90 
Closes #91

### CODE REVIEW

**Comment by gnarf** [comment]
https://github.com/bocoup/aria-at-gh-actions-helper-dev/actions/runs/16353859096/job/46208139042 is a test run using this branch - everything looks good

File: src/runner/driver-test-runner.js [hunk 1]
```diff
@@ -197,34 +197,18 @@ export class DriverTestRunner {
...
-        // vocalizations so that they do not leak into the output collected by
-        // whatever test is to follow. By setting the *undesired* value
-        // followed by the desired value, the harness can deterministically
-        // consume all such vocalizations.
-        //
-        // When JAWS supports the "getSettings" command, this logic should be
-        // simplified to first check the current state and only issue a
-        // "setSettings" command (for the desired value) when necessary.
-        //
-        // https://github.com/w3c/aria-at-automation-harness/issues/91
```
Comment (jugglinmike) [inline src/runner/driver-test-runner.js:213]: My novella nooooo

**Review by jugglinmike — APPROVED** [review]
Nicely done, @gnarf and (behind the scenes) @vtabota-fs!

**Comment by jugglinmike** [comment]
[Published in version 1.0.2](https://www.npmjs.com/package/@bocoup/aria-at-automation-harness/v/1.0.2)
